import type Database from 'better-sqlite3';

export const DEMO_TESTS = {
  tests: [
    { id: 'reading-a1', kind: 'reading', title: 'Reading — Academic Test 1: Climate & Architecture', durationSec: 3600 },
    { id: 'reading-a2', kind: 'reading', title: 'Reading — Academic Test 2: The Silk Road', durationSec: 3600 },
    { id: 'reading-g1', kind: 'reading', title: 'Reading — General Training Test 1: Workplace & Ads', durationSec: 3600 },
    { id: 'reading-official-40', kind: 'reading', title: 'Reading — Official 40-Q Mock (IELTS.org 46pp)', durationSec: 3600 },
    { id: 'listening-1', kind: 'listening', title: 'Listening — Test 1: Everyday Conversation + Lecture', durationSec: 1800 },
    { id: 'listening-2', kind: 'listening', title: 'Listening — Test 2: Campus & Academic Talk', durationSec: 1800 },
    { id: 'writing-a1', kind: 'writing', title: 'Writing — Academic Task 1 & 2 (Graphs + Essay)', durationSec: 3600 },
    { id: 'writing-g1', kind: 'writing', title: 'Writing — General Training (Letter + Essay)', durationSec: 3600 },
    { id: 'speaking-1', kind: 'speaking', title: 'Speaking — Part 1-3: Hometown & Technology', durationSec: 840 },
    { id: 'speaking-2', kind: 'speaking', title: 'Speaking — Part 1-3: Work & Environment', durationSec: 840 },
  ],
  passages: [
    { id: 'p-climate', title: 'The Climate-Responsive Architect', body: 'Passage 1 — The Climate-Responsive Architect\n\nIn the late 20th century, architecture began to reckon with climate not as a backdrop but as a client. Passive design — orientation, thermal mass, cross-ventilation — moved from vernacular footnote to performance metric. Glass towers, once celebrated for transparency, became case studies in solar gain. In response, practices like Foster and Rogers revisited courtyards, brise-soleil, and dense urban fabric. Recent studies of traditional housing in the Gulf show indoor temperatures 8-12°C lower than neighbouring modern blocks, despite no mechanical cooling. The lesson is not nostalgia but transfer: a wind catcher is a pressure system, not a style.\n\nPassage 2 — The Silk Road Reconsidered\n\nThe Silk Road is often imagined as a single thread from Chang’an to Venice. In reality it was a braid. Textual and archaeological evidence reveals at least three northern corridors and two southern maritime routes operating concurrently by the 8th century. Commodities moved unevenly: silk westward, glass eastward, but ideas — paper, decimal notation, Buddhist vinaya — moved fastest. The most telling find is not silk but Samarkand paper in a 9th-century Tibetan monastery, far from any “road” on European maps.' },
    { id: 'p-silk', title: 'The Silk Road Reconsidered (Extended)', body: 'Archaeologists now describe the Silk Road as overlapping networks rather than a single highway. Oases were not rests but markets where value was renegotiated. A caravan leaving Dunhuang might exchange bolts of silk for glass ingots in Bukhara, then for lapis in Merv, each leg repriced. The paper fragment from Samarkand found in Tibet suggests literacy moved alongside bales.' },
    { id: 'p-workplace', title: 'Workplace Notices — General Training', body: 'Section 1: Notices\nA: Staff canteen — Opening hours 7am-3pm, closed weekends. Hot meals 12-2pm only.\nB: Safety drill — Tuesday 10am, Assembly point B. Do not use lifts.\nC: Library — 3-week loans, fines 20p/day. Renew online.\n\nSection 2: Recruitment\nCompany X operates a two-stage interview: screening call, then panel. Panel includes line manager + HR. Candidates receive written feedback within 5 days.' },
    // Official 40-Q mock passages (from IELTS.org 46pp PDF)
    { id: 'p-off-rockets', title: 'Academic Reading — Rockets (Matching Features)', body: `The invention of rockets is linked inextricably with the invention of 'black powder'. Most historians of technology credit the Chinese with its discovery. They base their belief on studies of Chinese writings or on the notebooks of early Europeans who settled in or made long visits to China to study its history and civilisation. It is probable that, some time in the tenth century, black powder was first compounded from its basic ingredients of saltpetre, charcoal and sulphur. But this does not mean that it was immediately used to propel rockets. By the thirteenth century, powder-propelled fire arrows had become rather common. The Chinese relied on this type of technological development to produce incendiary projectiles of many sorts, explosive grenades and possibly cannons to repel their enemies. One such weapon was the 'basket of fire' or, as directly translated from Chinese, the 'arrows like flying leopards'. The 0.7 metre-long arrows, each with a long tube of gunpowder attached near the point of each arrow, could be fired from a long, octagonal-shaped basket at the same time and had a range of 400 paces. Another weapon was the 'arrow as a flying sabre', which could be fired from crossbows. The rocket, placed in a similar position to other rocket-propelled arrows, was designed to increase the range. A small iron weight was attached to the 1.5m bamboo shaft, just below the feathers, to increase the arrow's stability by moving the centre of gravity to a position below the rocket. At a similar time, the Arabs had developed the 'egg which moves and burns'. This 'egg' was apparently full of gunpowder and stabilised by a 1.5m tail. It was fired using two rockets attached to either side of this tail.

It was not until the eighteenth century that Europe became seriously interested in the possibilities of using the rocket itself as a weapon of war and not just to propel other weapons. Prior to this, rockets were used only in pyrotechnic displays. The incentive for the more aggressive use of rockets came not from within the European continent but from far-away India, whose leaders had built up a corps of rocketeers and used rockets successfully against the British in the late eighteenth century. The Indian rockets used against the British were described by a British Captain serving in India as 'an iron envelope about 200 millimetres long and 40 millimetres in diameter with sharp points at the top and a 3m-long bamboo guiding stick'. In the early nineteenth century the British began to experiment with incendiary barrage rockets. The British rocket differed from the Indian version in that it was completely encased in a stout, iron cylinder, terminating in a conical head, measuring one metre in diameter and having a stick almost five metres long and constructed in such a way that it could be firmly attached to the body of the rocket. The Americans developed a rocket, complete with its own launcher, to use against the Mexicans in the mid-nineteenth century. A long cylindrical tube was propped up by two sticks and fastened to the top of the launcher, thereby allowing the rockets to be inserted and lit from the other end. However, the results were sometimes not that impressive as the behaviour of the rockets in flight was less than predictable.` },
    { id: 'p-off-dung', title: 'Academic Reading — Dung Beetles (Table Completion)', body: `Introducing dung beetles into a pasture is a simple process: approximately 1,500 beetles are released, a handful at a time, into fresh cow pats in the cow pasture. The beetles immediately disappear beneath the pats digging and tunnelling and, if they successfully adapt to their new environment, soon become a permanent, self-sustaining part of the local ecology. In time they multiply and within three or four years the benefits to the pasture are obvious.

Dung beetles work from the inside of the pat so they are sheltered from predators such as birds and foxes. Most species burrow into the soil and bury dung in tunnels directly underneath the pats, which are hollowed out from within. Some large species originating from France excavate tunnels to a depth of approximately 30 cm below the dung pat. These beetles make sausage-shaped brood chambers along the tunnels. The shallowest tunnels belong to a much smaller Spanish species that buries dung in chambers that hang like fruit from the branches of a pear tree. South African beetles dig narrow tunnels of approximately 20 cm below the surface of the pat. Some surface-dwelling beetles, including a South African species, cut perfectly-shaped balls from the pat, which are rolled away and attached to the bases of plants.

For maximum dung burial in spring, summer and autumn, farmers require a variety of species with overlapping periods of activity. In the cooler environments of the state of Victoria, the large French species (2.5 cms long), is matched with smaller (half this size), temperate-climate Spanish species. The former are slow to recover from the winter cold and produce only one or two generations of offspring from late spring until autumn. The latter, which multiply rapidly in early spring, produce two to five generations annually. The South African ball-rolling species, being a sub-tropical beetle, prefers the climate of northern and coastal New South Wales where it commonly works with the South African tunneling species. In warmer climates, many species are active for longer periods of the year.

Glossary: dung: the droppings or excreta of animals; cow pats: droppings of cows` },
    { id: 'p-off-caloric', title: 'Academic Reading — Caloric Restriction Mimetic (Flow-chart)', body: `No treatment on the market today has been proved to slow human aging. But one intervention, consumption of a low-calorie yet nutritionally balanced diet, works incredibly well in a broad range of animals, increasing longevity and prolonging good health. Those findings suggest that caloric restriction could delay aging and increase longevity in humans, too. But what if someone could create a pill that mimicked the physiological effects of eating less without actually forcing people to eat less, a 'caloric-restriction mimetic'?

The best-studied candidate for a caloric-restriction mimetic, 2DG (2-deoxy-D-glucose), works by interfering with the way cells process glucose. It has proved toxic at some doses in animals and so cannot be used in humans. But it has demonstrated that chemicals can replicate the effects of caloric restriction; the trick is finding the right one.

Cells use the glucose from food to generate ATP (adenosine triphosphate), the molecule that powers many activities in the body. By limiting food intake, caloric restriction minimizes the amount of glucose entering cells and decreases ATP generation. When 2DG is administered to animals that eat normally, glucose reaches cells in abundance but the drug prevents most of it from being processed and thus reduces ATP synthesis. Researchers have proposed several explanations for why interruption of glucose processing and ATP production might retard aging. One possibility relates to the ATP-making machinery's emission of free radicals, which are thought to contribute to aging and to such age-related diseases as cancer by damaging cells. Reduced operation of the machinery should limit their production and thereby constrain the damage. Another hypothesis suggests that decreased processing of glucose could indicate to cells that food is scarce (even if it isn't) and induce them to shift into an anti-aging mode that emphasizes preservation of the organism over such 'luxuries' as growth and reproduction.` },
    { id: 'p-off-marie1', title: 'Academic Reading — Marie Curie (TFNG)', body: `Marie Curie is probably the most famous woman scientist who has ever lived. Born Maria Sklodowska in Poland in 1867, she is famous for her work on radioactivity, and was twice a winner of the Nobel Prize. With her husband, Pierre Curie, and Henri Becquerel, she was awarded the 1903 Nobel Prize for Physics, and was then sole winner of the 1911 Nobel Prize for Chemistry. She was the first woman to win a Nobel Prize.

From childhood, Marie was remarkable for her prodigious memory, and at the age of 16 won a gold medal on completion of her secondary education. Because her father lost his savings through bad investment, she then had to take work as a teacher. From her earnings she was able to finance her sister Bronia's medical studies in Paris, on the understanding that Bronia would, in turn, later help her to get an education.

In 1891 this promise was fulfilled and Marie went to Paris and began to study at the Sorbonne (the University of Paris). She often worked far into the night and lived on little more than bread and butter and tea. She came first in the examination in the physical sciences in 1893, and in 1894 was placed second in the examination in mathematical sciences. It was not until the spring of that year that she was introduced to Pierre Curie.` },
    { id: 'p-off-traffic', title: 'Academic Reading — Physics of Traffic (Headings)', body: `A Some years ago, when several theoretical physicists, principally Dirk Helbing and Boris Kerner of Stuttgart, Germany, began publishing papers on traffic flow in publications normally read by traffic engineers, they were clearly working outside their usual sphere of investigation. They had noticed that if they simulated the movement of vehicles on a highway, using the equations that describe how the molecules of a gas move, some very strange results emerged. Of course, vehicles do not behave exactly like gas molecules: for example, drivers try to avoid collisions by slowing down when they get too near another vehicle, whereas gas molecules have no such concern. However, the physicists modified the equations to take the differences into account and the overall description of traffic as a flowing gas has proved to be a very good one; the moving-gas model of traffic reproduces many phenomena seen in real-world traffic. The strangest thing that came out of these equations, however, was the implication that congestion can arise completely spontaneously; no external causes are necessary. Vehicles can be flowing freely along, at a density still well below what the road can handle, and then suddenly gel into a slow-moving ooze. Under the right conditions a brief and local fluctuation in the speed or the distance between vehicles is all it takes to trigger a system-wide breakdown that persists for hours.

B Though a decidedly unsettling discovery, this showed striking similarities to the phenomena popularized as 'chaos theory'. This theory has arisen from the understanding that in any complex interacting system which is made of many parts, each part affects the others. Consequently, tiny variations in one part of a complex system can grow in huge but unpredictable ways. This type of dramatic change from one state to another is similar to what happens when a chemical substance changes from a vapor to a liquid. It often happens that water in a cloud remains as a gas even after its temperature and density have reached the point where it could condense into water droplets. However, if the vapor encounters a solid surface, even something as small as a speck of dust, condensation can take place and the transition from vapor to liquid finally occurs.

C The physicists have challenged proposals to set a maximum capacity for vehicles on highways. They argue that it may not be enough simply to limit the rate at which vehicles are allowed to enter a highway, rather, it may be necessary to time each vehicle's entry onto a highway precisely to coincide with a temporary drop in the density of vehicles along the road.

D However, research into traffic control is generally centered in civil engineering departments and here the theories of the physicists have been greeted with some skepticism. Civil engineers favor a practical approach and believe traffic congestion is the result of poor road construction (two lanes becoming one lane or dangerous curves), which constricts the flow of traffic.

E James Banks, a professor of civil and environmental engineering at San Diego State University in the US, suggested that a sudden slowdown in traffic may have less to do with chaos theory than with driver psychology. As traffic gets heavier and the passing lane gets more crowded, aggressive drivers move to other lanes to try to pass, which also tends to even out the speed between lanes.` },
    { id: 'p-off-jewel', title: 'Academic Reading — The Jewel House (Sentence Endings)', body: `Deborah Harkness devotes her new book, The Jewel House, to the scientific community in 16th-century London. She argues that it is thanks to the imaginative collective efforts of the urban scientists that London became the melting pot in which a new mathematical and experimental culture crystallized. Harkness began her research by asking herself a new question: not what caused scientific revolution but what the names science and scientist meant in 16th-century London. Then she collected a vast range of sources, from printed books to scientific instruments and notebooks, and recorded, in a relational database, information on the men and women who produced them. Every chapter charts the activities of a particular community. For example, apothecaries settled in Lime Street, where they created a dense network of shops and gardens. Moreover, when Harkness reconstructs these groups, she provides dynamic analyses of their practices as these developed over time. In many cases, she makes clear, the alchemists of Elizabethan London already understood that knowledge had to rest not on authority but on familiarity through practice. Many of the 16th-century London scientists differed from the later ones of the 17th century. They saw themselves less as individuals out to gain fame, than as members of larger textual communities bent on exchanging and compiling information.` },
    { id: 'p-off-older1', title: 'Academic Reading — Older Workers (MCQ multi)', body: `Clearly, when older people do heavy physical work, their age may affect their productivity. But other skills may increase with age, including many that are crucial for good management, such as an ability to handle people diplomatically, to run a meeting or to spot a problem before it blows up. Peter Hicks, who co-ordinates OECD work on the policy implications of ageing, says that plenty of research suggests older people are paid more because they are worth more. And the virtues of the young may be exaggerated. 'The few companies that have kept on older workers find they have good judgement and their productivity is good,' says Peter Peterson. 'Besides, their education standards are much better than those of today's young high-school graduates.' Companies may say that older workers are not worth training because they are reaching the end of their working lives; in fact, young people tend to switch jobs so frequently that they offer the worst returns on training.` },
    { id: 'p-off-older2', title: 'Academic Reading — Older Workers & Bridge Jobs (MCQ single)', body: `The general assumption is that older workers are paid more in spite of, rather than because of, their productivity. That might partly explain why, when employers are under pressure to cut costs, they persuade a 55-year old to take early retirement. Take away seniority-based pay scales, and older workers may become a much more attractive employment proposition. But most employers and many workers are uncomfortable with the idea of reducing someone's pay in later life — although manual workers on piece-rates often earn less as they get older. One innovation was devised by IBM Belgium. Faced with the need to cut staff costs, and having decided to concentrate cuts on 55 to 60-year olds, IBM set up a separate company called Skill Team, which re-employed any of the early retired who wanted to go on working up to the age of 60. An employee who joined Skill Team at the age of 55 on a five-year contract would work for 58% of his time, over the full period, for 88% of his last IBM salary.

The best way to tempt the old to go on working may be to build on such 'bridge' jobs: part-time or temporary employment that creates a more gradual transition from full-time work to retirement. Studies have found that, in the United States, nearly half of all men and women who had been in full-time jobs in middle age moved into such 'bridge' jobs at the end of their working lives. In general, it is the best-paid and worst-paid who carry on working. There seem to be two very different types of bridge job-holder – those who continue working because they have to and those who continue working because they want to, even though they could afford to retire.` },
    { id: 'p-off-marie2', title: 'Academic Reading — Marie Curie Note Completion', body: `The marriage of Pierre and Marie Curie in 1895 marked the start of a partnership that was soon to achieve results of world significance. Following Henri Becquerel's discovery in 1896 of a new phenomenon, which Marie later called 'radioactivity', Marie Curie decided to find out if the radioactivity discovered in uranium was to be found in other elements. She discovered that this was true for thorium. Turning her attention to minerals, she found her interest drawn to pitchblende, a mineral whose radioactivity, superior to that of pure uranium, could be explained only by the presence in the ore of small quantities of an unknown substance of very high activity. Pierre Curie joined her in the work that she had undertaken to resolve this problem, and that led to the discovery of the new elements, polonium and radium. While Pierre Curie devoted himself chiefly to the physical study of the new radiations, Marie Curie struggled to obtain pure radium in the metallic state. This was achieved with the help of the chemist André-Louis Debierne. Based on the results of this research, Marie Curie received her Doctorate of Science, and in 1903 Marie and Pierre shared with Becquerel the Nobel Prize for Physics for the discovery of radioactivity.

The births of Marie's two daughters, Irène and Eve, in 1897 and 1904 failed to interrupt her scientific work. She was appointed lecturer in physics at the École Normale Supérieure for girls in Sèvres, France (1900), and introduced a method of teaching based on experimental demonstrations. In December 1904 she was appointed chief assistant in the laboratory directed by Pierre Curie. The sudden death of her husband in 1906 was a bitter blow to Marie Curie, but was also a turning point in her career: henceforth she was to devote all her energy to completing alone the scientific work that they had undertaken. On May 13, 1906, she was appointed to the professorship that had been left vacant on her husband's death, becoming the first woman to teach at the Sorbonne. In 1911 she was awarded the Nobel Prize for Chemistry for the isolation of a pure form of radium.` },
    { id: 'p-off-birds', title: 'Academic Reading — Origins of Birds (Sentence Completion)', body: `The science of evolutionary relationships has undergone a major change in recent decades. Following the work of German entomologist Willi Hennig, many evolutionary scientists now believe that the only features which carry any useful information are the evolutionary 'novelties' shared between organisms. The 'birds are dinosaurs' theory was first developed by English palaeontologist Thomas Huxley (1825–1895). He knew he was dealing with the lower leg bone (tibia) of a meat-eating, two-legged dinosaur belonging to the classification known as theropods, but attached to the tibia was an unidentified extra bone. On the menu that evening was quail, a small bird similar to a pheasant, and Huxley noticed the same strange bone, attached to the quail tibia on his plate. He later realised that it was in fact the bird's anklebone. More importantly, Huxley concluded that its forms in both dinosaur and bird skeletons were so similar that they must be closely related.

Huxley's idea fell out of favour for fifty years following the 1916 publication of The Origin of Birds by the Danish doctor Gerhard Heilmann. During this time, Heilmann's theory was widely accepted. Heilmann had noted that two-legged, meat-eating dinosaurs lacked collarbones. In later evolutionary stages these bones fuse together to form the distinctive 'Y'-shaped bone in a bird's neck, known as the furcula. Then, in the late 1960s, John Ostrom from Yale University in the US, noted 22 features in the skeletons of meat-eating dinosaurs that were also found in birds and nowhere else.

Most people on either side of the debate do accept, however, that the ancient winged creature known as Archaeopteryx is an ancestor of today's birds. Over the last few decades several dinosaurs with bird-like features and primitive birds with dinosaur-like features have been found in several countries, connecting Archaeopteryx back to dinosaurs, and forwards to modern birds.` },
    { id: 'p-off-lang', title: 'Academic Reading — Language (Summary list)', body: `Of all mankind's manifold creations, language must take pride of place. Other inventions – the wheel, agriculture, sliced bread – may have transformed our material existence, but the advent of language is what made us human. Compared to language, all other inventions pale in significance, since everything we have ever achieved depends on language and originates from it. But language is foremost not just because it came first. In its own right it is a tool of extraordinary sophistication, yet based on an idea of ingenious simplicity: 'this marvellous invention of composing out of twenty-five or thirty sounds that infinite variety of expressions which, whilst having in themselves no likeness to what is in our mind, allow us to disclose to others its whole secret.' Language is mankind's greatest invention – except, of course, that it was never invented. This apparent paradox is at the core of our fascination with language, and it holds many of its secrets.` },
    { id: 'p-off-plain', title: 'Academic Reading — Plain English (Summary text)', body: `The instructions accompanying do-it-yourself products are regularly cited as a source of unnecessary expense or frustration. Few companies seem to test their instructions by having them followed by a first-time user. Often, essential information is omitted, steps in the construction process are taken for granted, and some degree of special knowledge is assumed. This is especially worrying in any fields where failure to follow correct procedures can be dangerous. Objections to material in plain English have come mainly from the legal profession. Lawyers point to the risk of ambiguity inherent in the use of everyday language for legal or official documents, and draw attention to the need for confidence in legal formulations, which can come only from using language that has been tested in courts over the course of centuries.` },
    { id: 'p-off-greenhouse', title: 'Academic Reading — Seawater Greenhouse (Diagram)', body: `Charlie Paton has built a giant structure on a desert island off Abu Dhabi in the Persian Gulf – the first commercially viable version of his 'seawater greenhouse'. Local scientists, working with Paton under a licence from his company Light Works, are watering the desert and growing vegetables in what is basically a giant dew-making machine that produces fresh water and cool air from sun and seawater. The design has three main features. Firstly, there is a front wall of perforated cardboard through which hot, dry air blows in from the desert. This wall is kept moist by seawater pumped up from the nearby shoreline. As this water evaporates, heat is taken from the air inside the greenhouse and moisture added to it.

The second feature also serves to cool the air for the plants. Paton has constructed a double-layered roof with an outer layer of clear polythene and an inner, coated layer that reflects infrared light. Visible light can stream through to maximise photosynthesis, while infrared radiation is trapped in the space between the layers, away from the plants.

At the back of the greenhouse sits the third element, the main water-production unit. Just before entering this unit, the humid air of the greenhouse mixes with the hot, dry air from between the two layers of the roof. This means the air can absorb more moisture as it passes through a second perforated cardboard wall. Finally, the hot saturated air hits a condenser. This is kept cool by still more seawater. Drops of pure distilled water form on the condenser and flow into a tank for irrigating the crops.` },
  ],
  sections: [
    { id: 's-ra1-1', testId: 'reading-a1', type: 'reading', title: 'Passage 1 — Climate', passageId: 'p-climate' },
    { id: 's-ra1-2', testId: 'reading-a1', type: 'reading', title: 'Passage 2 — Silk Road', passageId: 'p-silk' },
    { id: 's-ra2-1', testId: 'reading-a2', type: 'reading', title: 'Passage 1 — Silk Road', passageId: 'p-silk' },
    { id: 's-rg1-1', testId: 'reading-g1', type: 'reading', title: 'Sections 1-2 — Notices', passageId: 'p-workplace' },
    // Official 40-Q mock — 12 sections covering all task types from PDF
    { id: 's-off-1', testId: 'reading-official-40', type: 'reading', title: 'Section 1 — Rockets: Matching Features (Q1-4)', passageId: 'p-off-rockets' },
    { id: 's-off-2', testId: 'reading-official-40', type: 'reading', title: 'Section 2 — Dung Beetles: Table Completion (Q5-9)', passageId: 'p-off-dung' },
    { id: 's-off-3', testId: 'reading-official-40', type: 'reading', title: 'Section 3 — Caloric Mimetic: Flow-chart (Q10-12)', passageId: 'p-off-caloric' },
    { id: 's-off-4', testId: 'reading-official-40', type: 'reading', title: 'Section 4 — Marie Curie: TFNG (Q13-15)', passageId: 'p-off-marie1' },
    { id: 's-off-5', testId: 'reading-official-40', type: 'reading', title: 'Section 5 — Traffic: Matching Headings (Q16-19)', passageId: 'p-off-traffic' },
    { id: 's-off-6', testId: 'reading-official-40', type: 'reading', title: 'Section 6 — Jewel House: Sentence Endings (Q20-22)', passageId: 'p-off-jewel' },
    { id: 's-off-7', testId: 'reading-official-40', type: 'reading', title: 'Section 7 — Older Workers: MC Multi (Q23-26)', passageId: 'p-off-older1' },
    { id: 's-off-8', testId: 'reading-official-40', type: 'reading', title: 'Section 8 — Older Workers: MC Single (Q27-30)', passageId: 'p-off-older2' },
    { id: 's-off-9', testId: 'reading-official-40', type: 'reading', title: 'Section 9 — Marie Curie Notes (Q31-36)', passageId: 'p-off-marie2' },
    { id: 's-off-10', testId: 'reading-official-40', type: 'reading', title: 'Section 10 — Birds: Sentence Completion (Q37-40)', passageId: 'p-off-birds' },
    { id: 's-l1-1', testId: 'listening-1', type: 'listening', title: 'Part 1 — Everyday Conversation', passageId: null, audioPath: null },
    { id: 's-l1-2', testId: 'listening-1', type: 'listening', title: 'Part 2 — Facilities Talk', passageId: null, audioPath: null },
    { id: 's-l1-3', testId: 'listening-1', type: 'listening', title: 'Part 3 — Tutorial Discussion', passageId: null, audioPath: null },
    { id: 's-l1-4', testId: 'listening-1', type: 'listening', title: 'Part 4 — Academic Lecture', passageId: null, audioPath: null },
    { id: 's-l2-1', testId: 'listening-2', type: 'listening', title: 'Listening Test 2 — 4 Parts', passageId: null, audioPath: null },
    { id: 's-wa1', testId: 'writing-a1', type: 'writing', title: 'Academic Writing — Task 1 & 2', passageId: null },
    { id: 's-wg1', testId: 'writing-g1', type: 'writing', title: 'General Writing — Letter & Essay', passageId: null },
    { id: 's-sp1-1', testId: 'speaking-1', type: 'speaking', title: 'Part 1 — Hometown & Daily Life (4-5 min)', passageId: null },
    { id: 's-sp1-2', testId: 'speaking-1', type: 'speaking', title: 'Part 2 — Cue Card: Describe a building you admire (2 min + 1 min prep)', passageId: null },
    { id: 's-sp1-3', testId: 'speaking-1', type: 'speaking', title: 'Part 3 — Discussion: Architecture & Environment (4-5 min)', passageId: null },
    { id: 's-sp2-1', testId: 'speaking-2', type: 'speaking', title: 'Speaking Test 2 — Work & Environment', passageId: null },
  ],
  questions: [
    // Reading A1 — Passage 1 Climate (4 Qs checked)
    { id: 'q-ra1-1', sectionId: 's-ra1-1', qType: 'TFNG', prompt: JSON.stringify('Traditional Gulf housing is cooler than modern blocks without air-conditioning.'), options: JSON.stringify(['True', 'False', 'Not Given']), answer: JSON.stringify('True'), marks: 1 },
    { id: 'q-ra1-2', sectionId: 's-ra1-1', qType: 'TFNG', prompt: JSON.stringify('Glass towers were originally designed to reduce solar gain.'), options: JSON.stringify(['True', 'False', 'Not Given']), answer: JSON.stringify('False'), marks: 1 },
    { id: 'q-ra1-3', sectionId: 's-ra1-1', qType: 'MCQ', prompt: JSON.stringify('What does the author say about wind catchers?'), options: JSON.stringify(['They are decorative only', 'They are a pressure system, not a style', 'They were invented in the 20th century', 'They increase solar gain']), answer: JSON.stringify('They are a pressure system, not a style'), marks: 1 },
    { id: 'q-ra1-4', sectionId: 's-ra1-1', qType: 'YNNG', prompt: JSON.stringify("The writer believes modern architects should copy traditional buildings exactly."), options: JSON.stringify(['Yes', 'No', 'Not Given']), answer: JSON.stringify('No'), marks: 1 },
    // Reading A1 — Passage 2 Silk Road (4 checked)
    { id: 'q-ra1-5', sectionId: 's-ra1-2', qType: 'MCQ', prompt: JSON.stringify('How many corridors operated concurrently by the 8th century?'), options: JSON.stringify(['One', 'Two', 'At least five', 'Three']), answer: JSON.stringify('At least five'), marks: 1 },
    { id: 'q-ra1-6', sectionId: 's-ra1-2', qType: 'TFNG', prompt: JSON.stringify('The Samarkand paper found in Tibet was on a mapped European Silk Road route.'), options: JSON.stringify(['True', 'False', 'Not Given']), answer: JSON.stringify('False'), marks: 1 },
    { id: 'q-ra1-7', sectionId: 's-ra1-2', qType: 'TFNG', prompt: JSON.stringify('Oases were only resting places, not markets.'), options: JSON.stringify(['True', 'False', 'Not Given']), answer: JSON.stringify('False'), marks: 1 },
    { id: 'q-ra1-8', sectionId: 's-ra1-2', qType: 'MCQ', prompt: JSON.stringify('What moved fastest along the routes?'), options: JSON.stringify(['Silk', 'Glass', 'Ideas — paper, decimals, Buddhist texts', 'Lapis']), answer: JSON.stringify('Ideas — paper, decimals, Buddhist texts'), marks: 1 },
    // Reading A2 — full 8 checked (uses same passages but different Qs)
    { id: 'q-ra2-1', sectionId: 's-ra2-1', qType: 'TFNG', prompt: JSON.stringify('The Silk Road was a single highway from Chang’an to Venice.'), options: JSON.stringify(['True', 'False', 'Not Given']), answer: JSON.stringify('False'), marks: 1 },
    { id: 'q-ra2-2', sectionId: 's-ra2-1', qType: 'MCQ', prompt: JSON.stringify('A caravan from Dunhuang exchanged silk for what in Bukhara?'), options: JSON.stringify(['Lapis', 'Glass ingots', 'Paper', 'Spices']), answer: JSON.stringify('Glass ingots'), marks: 1 },
    { id: 'q-ra2-3', sectionId: 's-ra2-1', qType: 'YNNG', prompt: JSON.stringify("The author argues archaeologists now see the Silk Road as multiple overlapping networks."), options: JSON.stringify(['Yes', 'No', 'Not Given']), answer: JSON.stringify('Yes'), marks: 1 },
    { id: 'q-ra2-4', sectionId: 's-ra2-1', qType: 'SENTENCE_COMPLETION', prompt: JSON.stringify('Paper from Samarkand was found in a _____ monastery.'), options: JSON.stringify(null), answer: JSON.stringify('Tibetan'), marks: 1 },
    { id: 'q-ra2-5', sectionId: 's-ra2-1', qType: 'TFNG', prompt: JSON.stringify('Caravan prices were fixed and never renegotiated at oases.'), options: JSON.stringify(['True', 'False', 'Not Given']), answer: JSON.stringify('False'), marks: 1 },
    { id: 'q-ra2-6', sectionId: 's-ra2-1', qType: 'MCQ', prompt: JSON.stringify('What does the author say about the most telling find?'), options: JSON.stringify(['Silk in Venice', 'Glass in Tibet', 'Paper far from mapped roads', 'Lapis in Chang’an']), answer: JSON.stringify('Paper far from mapped roads'), marks: 1 },
    // Reading G1 — General (4 checked)
    { id: 'q-rg1-1', sectionId: 's-rg1-1', qType: 'MCQ', prompt: JSON.stringify('When is the safety drill?'), options: JSON.stringify(['Monday 10am', 'Tuesday 10am', 'Tuesday 2pm', 'Wednesday 10am']), answer: JSON.stringify('Tuesday 10am'), marks: 1 },
    { id: 'q-rg1-2', sectionId: 's-rg1-1', qType: 'SENTENCE_COMPLETION', prompt: JSON.stringify('Library fines are _____ per day.'), options: JSON.stringify(null), answer: JSON.stringify('20p'), marks: 1 },
    { id: 'q-rg1-3', sectionId: 's-rg1-1', qType: 'MCQ', prompt: JSON.stringify('How long are library loans?'), options: JSON.stringify(['1 week', '2 weeks', '3 weeks', '1 month']), answer: JSON.stringify('3 weeks'), marks: 1 },
    { id: 'q-rg1-4', sectionId: 's-rg1-1', qType: 'TFNG', prompt: JSON.stringify('Recruitment feedback arrives within 5 days.'), options: JSON.stringify(['True', 'False', 'Not Given']), answer: JSON.stringify('True'), marks: 1 },
    // Listening 1 — 8 checked across 4 parts
    { id: 'q-l1-1', sectionId: 's-l1-1', qType: 'FORM_COMPLETION', prompt: JSON.stringify('Form: Name: ______'), options: JSON.stringify(null), answer: JSON.stringify('Sofia Patel'), marks: 1 },
    { id: 'q-l1-2', sectionId: 's-l1-1', qType: 'FORM_COMPLETION', prompt: JSON.stringify('Form: Phone: ______'), options: JSON.stringify(null), answer: JSON.stringify('07700900123'), marks: 1 },
    { id: 'q-l1-3', sectionId: 's-l1-1', qType: 'MCQ', prompt: JSON.stringify('What time is the meeting?'), options: JSON.stringify(['9:00', '10:00', '11:30', '2:00']), answer: JSON.stringify('10:00'), marks: 1 },
    { id: 'q-l1-4', sectionId: 's-l1-2', qType: 'MAP_LABEL', prompt: JSON.stringify('Library is at ____ on the campus map.'), options: JSON.stringify(['A', 'B', 'C', 'D']), answer: JSON.stringify('B'), marks: 1 },
    { id: 'q-l1-5', sectionId: 's-l1-2', qType: 'MCQ', prompt: JSON.stringify('Canteen hot meals are available:'), options: JSON.stringify(['7am-3pm', '12-2pm only', 'Weekends only', 'Never']), answer: JSON.stringify('12-2pm only'), marks: 1 },
    { id: 'q-l1-6', sectionId: 's-l1-3', qType: 'MCQ', prompt: JSON.stringify('The tutor says the deadline is:'), options: JSON.stringify(['Fixed', 'Extended to Friday', 'Cancelled', 'Next month']), answer: JSON.stringify('Extended to Friday'), marks: 1 },
    { id: 'q-l1-7', sectionId: 's-l1-4', qType: 'SENTENCE_COMPLETION', prompt: JSON.stringify('The lecture argues urban density reduces _____.'), options: JSON.stringify(null), answer: JSON.stringify('energy use'), marks: 1 },
    { id: 'q-l1-8', sectionId: 's-l1-4', qType: 'SENTENCE_COMPLETION', prompt: JSON.stringify('Wind catchers are described as a _____ system.'), options: JSON.stringify(null), answer: JSON.stringify('pressure'), marks: 1 },
    // Listening 2 — 6 checked
    { id: 'q-l2-1', sectionId: 's-l2-1', qType: 'MCQ', prompt: JSON.stringify('Where is the student enrolling?'), options: JSON.stringify(['Library', 'Engineering', 'Business School', 'Medicine']), answer: JSON.stringify('Business School'), marks: 1 },
    { id: 'q-l2-2', sectionId: 's-l2-1', qType: 'FORM_COMPLETION', prompt: JSON.stringify('Student ID: ______'), options: JSON.stringify(null), answer: JSON.stringify('B202489'), marks: 1 },
    { id: 'q-l2-3', sectionId: 's-l2-1', qType: 'MAP_LABEL', prompt: JSON.stringify('Seminar room is at ____.'), options: JSON.stringify(['A', 'B', 'C']), answer: JSON.stringify('C'), marks: 1 },
    { id: 'q-l2-4', sectionId: 's-l2-1', qType: 'MCQ', prompt: JSON.stringify('The professor recommends:'), options: JSON.stringify(['More reading', 'Group work', 'Field trip', 'No change']), answer: JSON.stringify('Group work'), marks: 1 },
    { id: 'q-l2-5', sectionId: 's-l2-1', qType: 'SENTENCE_COMPLETION', prompt: JSON.stringify('The assignment is due on _____.'), options: JSON.stringify(null), answer: JSON.stringify('Friday'), marks: 1 },
    // Writing — checked via Nemotron AI (model answers stored for reference, band scored)
    { id: 'q-wa1-1', sectionId: 's-wa1', qType: 'WRITING_TASK1', prompt: JSON.stringify('Task 1 (Academic): The chart shows energy use by sector in 2020 vs 2023. Describe the main trends (≥150 words, 20 min).'), options: JSON.stringify(null), answer: JSON.stringify('Model: Overview — industry fell 12% while services rose 9%; details compare 2020: industry 35% vs services 28%, 2023: industry 23% vs services 37%; notable transport stable at 20%. Use data, no opinion, 150+ words.'), marks: 1 },
    { id: 'q-wa1-2', sectionId: 's-wa1', qType: 'WRITING_TASK2', prompt: JSON.stringify('Task 2: Some say architecture should prioritize beauty over sustainability. Discuss both views and give your opinion (≥250 words, 40 min).'), options: JSON.stringify(null), answer: JSON.stringify('Model Band 9: intro paraphrase, body 1 beauty (identity, wellbeing), body 2 sustainability (climate, lifecycle), clear position: sustainability as prerequisite, examples Gulf housing vs glass tower, cohesive + less-common vocab.'), marks: 1 },
    { id: 'q-wg1-1', sectionId: 's-wg1', qType: 'WRITING_TASK1', prompt: JSON.stringify('Task 1 (General): You missed a job interview. Write a letter to the employer explaining and requesting another chance (≥150 words).'), options: JSON.stringify(null), answer: JSON.stringify('Model: Dear Sir/Madam, apologize for missing interview due to train cancellation, explain + evidence, request reschedule, propose dates, formal tone, 150+ words.'), marks: 1 },
    { id: 'q-wg1-2', sectionId: 's-wg1', qType: 'WRITING_TASK2', prompt: JSON.stringify('Task 2 (General): Some employers prefer academic qualifications over life skills. Discuss and give your opinion (≥250 words).'), options: JSON.stringify(null), answer: JSON.stringify('Model: balanced discussion, examples internships vs degrees, position: blend, CC/LR/GRA focus.'), marks: 1 },
    // Speaking — checked via Parakeet transcript + Nemotron FC/LR/GRA/P (model prompts stored)
    { id: 'q-sp1-1', sectionId: 's-sp1-1', qType: 'SPEAKING_PART1', prompt: JSON.stringify('Part 1: Describe your hometown. What do you like most about it?'), options: JSON.stringify(null), answer: JSON.stringify('Check: fluency, 2-3 sentences, past/present mix, less-common vocab. Model: My hometown is a coastal town... I cherish the evening promenade...'), marks: 1 },
    { id: 'q-sp1-2', sectionId: 's-sp1-1', qType: 'SPEAKING_PART1', prompt: JSON.stringify('Part 1: Do you work or study? What do you enjoy about it?'), options: JSON.stringify(null), answer: JSON.stringify('Check: present habits, like/enjoy + reason. Model: I study architecture; I relish studio critiques...'), marks: 1 },
    { id: 'q-sp1-3', sectionId: 's-sp1-2', qType: 'SPEAKING_PART2', prompt: JSON.stringify('Part 2 Cue: Describe a building you admire. 1m prep + 2m talk. Where, what it looks like, why you admire it.'), options: JSON.stringify(null), answer: JSON.stringify('Check: 1-2 min, past tense, discourse markers, P. Model: The wind-catcher house in Yazd, mud-brick, pressure system...'), marks: 1 },
    { id: 'q-sp1-4', sectionId: 's-sp1-3', qType: 'SPEAKING_PART3', prompt: JSON.stringify('Part 3: Should governments fund historic preservation? Why?'), options: JSON.stringify(null), answer: JSON.stringify('Check: abstract, conditionals, GRA. Model: If funds are scarce, prioritise... cultural continuity vs housing...'), marks: 1 },
    { id: 'q-sp2-1', sectionId: 's-sp2-1', qType: 'SPEAKING_PART1', prompt: JSON.stringify('Part 1: What do you do in your free time?'), options: JSON.stringify(null), answer: JSON.stringify('Model: I sketch streetscapes, which sharpens observation...'), marks: 1 },
    { id: 'q-sp2-2', sectionId: 's-sp2-1', qType: 'SPEAKING_PART2', prompt: JSON.stringify('Part 2 Cue: Describe a time you had to be punctual. 1m prep + 2m talk.'), options: JSON.stringify(null), answer: JSON.stringify('Model: Missed train to interview, apology letter...'), marks: 1 },
    { id: 'q-sp2-3', sectionId: 's-sp2-1', qType: 'SPEAKING_PART3', prompt: JSON.stringify('Part 3: Is punctuality more important now than in the past?'), options: JSON.stringify(null), answer: JSON.stringify('Model: Gig economy, scheduling apps increase expectation...'), marks: 1 },
    // Official 40-Q mock — checked answers from PDF answer keys (pp.5,8,11,14,18,22,26,29,33,37)
    // Q1-4 Matching Features (rockets) — NB any letter more than once
    { id: 'q-off-1', sectionId: 's-off-1', qType: 'MATCHING_FEATURES', prompt: JSON.stringify('Q1 — Match: black powder — First invented or used by? A Chinese B Indians C British D Arabs E Americans'), options: JSON.stringify(['A the Chinese','B the Indians','C the British','D the Arabs','E the Americans']), answer: JSON.stringify('A'), marks: 1 },
    { id: 'q-off-2', sectionId: 's-off-1', qType: 'MATCHING_FEATURES', prompt: JSON.stringify('Q2 — Match: rocket-propelled arrows for fighting'), options: JSON.stringify(['A the Chinese','B the Indians','C the British','D the Arabs','E the Americans']), answer: JSON.stringify('A'), marks: 1 },
    { id: 'q-off-3', sectionId: 's-off-1', qType: 'MATCHING_FEATURES', prompt: JSON.stringify('Q3 — Match: rockets as war weapons'), options: JSON.stringify(['A the Chinese','B the Indians','C the British','D the Arabs','E the Americans']), answer: JSON.stringify('B'), marks: 1 },
    { id: 'q-off-4', sectionId: 's-off-1', qType: 'MATCHING_FEATURES', prompt: JSON.stringify('Q4 — Match: the rocket launcher'), options: JSON.stringify(['A the Chinese','B the Indians','C the British','D the Arabs','E the Americans']), answer: JSON.stringify('E'), marks: 1 },
    // Q5-9 Table Completion dung beetles — NO MORE THAN THREE WORDS
    { id: 'q-off-5', sectionId: 's-off-2', qType: 'TABLE_COMPLETION', prompt: JSON.stringify('Q5 — Table: Spanish species — Preferred climate: 9 ............'), options: JSON.stringify(null), answer: JSON.stringify('temperate'), marks: 1 },
    { id: 'q-off-6', sectionId: 's-off-2', qType: 'TABLE_COMPLETION', prompt: JSON.stringify('Q6 — Table: Spanish species — Start of active period: 10 ............'), options: JSON.stringify(null), answer: JSON.stringify('early spring'), marks: 1 },
    { id: 'q-off-7', sectionId: 's-off-2', qType: 'TABLE_COMPLETION', prompt: JSON.stringify('Q7 — Table: Spanish species — Generations per year: 11 ............'), options: JSON.stringify(null), answer: JSON.stringify('two to five / 2-5'), marks: 1 },
    { id: 'q-off-8', sectionId: 's-off-2', qType: 'TABLE_COMPLETION', prompt: JSON.stringify('Q8 — Table: South African ball roller — Preferred climate: 12 ............'), options: JSON.stringify(null), answer: JSON.stringify('sub-tropical'), marks: 1 },
    { id: 'q-off-9', sectionId: 's-off-2', qType: 'TABLE_COMPLETION', prompt: JSON.stringify('Q9 — Table: South African ball roller — Complementary species: 13 ............'), options: JSON.stringify(null), answer: JSON.stringify('South African tunneling/tunnelling'), marks: 1 },
    // Q10-12 Flow-chart caloric — NO MORE THAN TWO WORDS
    { id: 'q-off-10', sectionId: 's-off-3', qType: 'FLOW_CHART', prompt: JSON.stringify('Q10 — Flow-chart: CR mimetic → less 1 ............ is processed'), options: JSON.stringify(null), answer: JSON.stringify('glucose'), marks: 1 },
    { id: 'q-off-11', sectionId: 's-off-3', qType: 'FLOW_CHART', prompt: JSON.stringify('Q11 — Flow-chart: Theory 1: fewer 2 ............ are emitted'), options: JSON.stringify(null), answer: JSON.stringify('free radicals'), marks: 1 },
    { id: 'q-off-12', sectionId: 's-off-3', qType: 'FLOW_CHART', prompt: JSON.stringify('Q12 — Flow-chart: Theory 2: cells focus on 3 ............ because food is scarce'), options: JSON.stringify(null), answer: JSON.stringify('preservation'), marks: 1 },
    // Q13-15 TFNG Marie Curie (short)
    { id: 'q-off-13', sectionId: 's-off-4', qType: 'TFNG', prompt: JSON.stringify("Q13 — Marie Curie's husband was a joint winner of both Marie's Nobel Prizes."), options: JSON.stringify(['True','False','Not Given']), answer: JSON.stringify('FALSE'), marks: 1 },
    { id: 'q-off-14', sectionId: 's-off-4', qType: 'TFNG', prompt: JSON.stringify('Q14 — Marie became interested in science when she was a child.'), options: JSON.stringify(['True','False','Not Given']), answer: JSON.stringify('NOT GIVEN'), marks: 1 },
    { id: 'q-off-15', sectionId: 's-off-4', qType: 'TFNG', prompt: JSON.stringify("Q15 — Marie was able to attend the Sorbonne because of her sister's financial contribution."), options: JSON.stringify(['True','False','Not Given']), answer: JSON.stringify('TRUE'), marks: 1 },
    // Q16-19 Matching Headings traffic — Sections C,D,E (B is example i)
    { id: 'q-off-16', sectionId: 's-off-5', qType: 'MATCHING_HEADINGS', prompt: JSON.stringify('Q16 — Section C: Choose heading i-viii'), options: JSON.stringify(['i Dramatic effects','ii Maths experiment reduced congestion','iii Concept from one field applied in another','iv Lack of investment','v Areas of doubt','vi How countries dealt','vii Impact of driver behaviour','viii Proposal to take control']), answer: JSON.stringify('iii'), marks: 1 },
    { id: 'q-off-17', sectionId: 's-off-5', qType: 'MATCHING_HEADINGS', prompt: JSON.stringify('Q17 — Section D: Choose heading i-viii'), options: JSON.stringify(['i','ii','iii','iv','v','vi','vii','viii']), answer: JSON.stringify('viii'), marks: 1 },
    { id: 'q-off-18', sectionId: 's-off-5', qType: 'MATCHING_HEADINGS', prompt: JSON.stringify('Q18 — Section D (second question per PDF p.18: actually Section D heading)'), options: JSON.stringify(['i','ii','iii','iv','v','vi','vii','viii']), answer: JSON.stringify('v'), marks: 1 },
    { id: 'q-off-19', sectionId: 's-off-5', qType: 'MATCHING_HEADINGS', prompt: JSON.stringify('Q19 — Section E: Choose heading i-viii'), options: JSON.stringify(['i','ii','iii','iv','v','vi','vii','viii']), answer: JSON.stringify('vii'), marks: 1 },
    // Q20-22 Matching Sentence Endings Jewel House
    { id: 'q-off-20', sectionId: 's-off-6', qType: 'MATCHING_SENTENCE_ENDINGS', prompt: JSON.stringify("Q20 — Harkness's research method was different because"), options: JSON.stringify(['A greatest knowledge','B started by understanding terms','C worked as individuals','D examined how methods evolved','E Clement Draper best','F used old ways for new purposes']), answer: JSON.stringify('B'), marks: 1 },
    { id: 'q-off-21', sectionId: 's-off-6', qType: 'MATCHING_SENTENCE_ENDINGS', prompt: JSON.stringify("Q21 — Harkness's reconstruction was new because"), options: JSON.stringify(['A','B','C','D','E','F']), answer: JSON.stringify('D'), marks: 1 },
    { id: 'q-off-22', sectionId: 's-off-6', qType: 'MATCHING_SENTENCE_ENDINGS', prompt: JSON.stringify('Q22 — 16th-century scientists were innovative because'), options: JSON.stringify(['A','B','C','D','E','F']), answer: JSON.stringify('F'), marks: 1 },
    // Q23-26 MC more than one — Choose TWO letters
    { id: 'q-off-23', sectionId: 's-off-7', qType: 'MCQ_MULTI', prompt: JSON.stringify('Q23 — Advantages of older workers: Choose TWO — B They can predict trouble OR G More skilled in personal relationships (1 of 2)'), options: JSON.stringify(['A careless accidents','B predict trouble','C train younger','D unexpected problems','E conscientious','F lower salaries','G personal relationships']), answer: JSON.stringify('B'), marks: 1 },
    { id: 'q-off-24', sectionId: 's-off-7', qType: 'MCQ_MULTI', prompt: JSON.stringify('Q24 — Advantages: Choose second answer (B/G pair)'), options: JSON.stringify(['A','B','C','D','E','F','G']), answer: JSON.stringify('G'), marks: 1 },
    { id: 'q-off-25', sectionId: 's-off-7', qType: 'MCQ_MULTI', prompt: JSON.stringify('Q25 — Disadvantages of younger workers: Choose TWO — C Do not stay long OR E Not as well educated (1 of 2)'), options: JSON.stringify(['A too confident','B injure','C do not stay','D theoretical','E not as well educated','F demand higher']), answer: JSON.stringify('C'), marks: 1 },
    { id: 'q-off-26', sectionId: 's-off-7', qType: 'MCQ_MULTI', prompt: JSON.stringify('Q26 — Disadvantages second answer (C/E pair)'), options: JSON.stringify(['A','B','C','D','E','F']), answer: JSON.stringify('E'), marks: 1 },
    // Q27-30 MC one answer — older workers bridge jobs
    { id: 'q-off-27', sectionId: 's-off-8', qType: 'MCQ', prompt: JSON.stringify('Q27 — In paragraph 1, writer suggests companies could consider'), options: JSON.stringify(['A abolishing pay schemes based on age','B avoiding piece-rates','C increasing pay','D equipping with skills']), answer: JSON.stringify('A'), marks: 1 },
    { id: 'q-off-28', sectionId: 's-off-8', qType: 'MCQ', prompt: JSON.stringify('Q28 — Skill Team is an example of a company which'), options: JSON.stringify(['A offers increases','B allows continue as long as they want','C allows expertise to be put to use','D treats equally']), answer: JSON.stringify('C'), marks: 1 },
    { id: 'q-off-29', sectionId: 's-off-8', qType: 'MCQ', prompt: JSON.stringify("Q29 — According to writer, 'bridge' jobs"), options: JSON.stringify(['A attract middle-salary','B better paid','C originated US','D appeal to distinct groups']), answer: JSON.stringify('D'), marks: 1 },
    { id: 'q-off-30', sectionId: 's-off-8', qType: 'MCQ', prompt: JSON.stringify("Q30 — David Storey's study found that"), options: JSON.stringify(['A demand more','B older good at running businesses','C increasing self-employed','D few young have businesses']), answer: JSON.stringify('B'), marks: 1 },
    // Q31-36 Note Completion Marie Curie long — ONE WORD ONLY
    { id: 'q-off-31', sectionId: 's-off-9', qType: 'NOTE_COMPLETION', prompt: JSON.stringify('Q31 — When uranium was discovered radioactive, Marie found element 1 ........ had same property.'), options: JSON.stringify(null), answer: JSON.stringify('thorium'), marks: 1 },
    { id: 'q-off-32', sectionId: 's-off-9', qType: 'NOTE_COMPLETION', prompt: JSON.stringify('Q32 — Mineral 2 ........ led to discovery of two new elements.'), options: JSON.stringify(null), answer: JSON.stringify('pitchblende'), marks: 1 },
    { id: 'q-off-33', sectionId: 's-off-9', qType: 'NOTE_COMPLETION', prompt: JSON.stringify('Q33 — In 1911, Marie received recognition for work on element 3 ........ .'), options: JSON.stringify(null), answer: JSON.stringify('radium'), marks: 1 },
    { id: 'q-off-34', sectionId: 's-off-9', qType: 'NOTE_COMPLETION', prompt: JSON.stringify('Q34 — Marie and Irene developed X-radiography for 4 ........ .'), options: JSON.stringify(null), answer: JSON.stringify('soldiers'), marks: 1 },
    { id: 'q-off-35', sectionId: 's-off-9', qType: 'NOTE_COMPLETION', prompt: JSON.stringify('Q35 — Marie saw importance of collecting material for research and for cases of 5 ........ .'), options: JSON.stringify(null), answer: JSON.stringify('illness'), marks: 1 },
    { id: 'q-off-36', sectionId: 's-off-9', qType: 'NOTE_COMPLETION', prompt: JSON.stringify('Q36 — Stock in Paris contributed to discovery of 6 ........ and artificial radioactivity.'), options: JSON.stringify(null), answer: JSON.stringify('neutron'), marks: 1 },
    // Q37-40 Sentence Completion birds — ONE WORD ONLY
    { id: 'q-off-37', sectionId: 's-off-10', qType: 'SENTENCE_COMPLETION', prompt: JSON.stringify('Q37 — Huxley studied dinosaur belonging to group called ........ .'), options: JSON.stringify(null), answer: JSON.stringify('theropods'), marks: 1 },
    { id: 'q-off-38', sectionId: 's-off-10', qType: 'SENTENCE_COMPLETION', prompt: JSON.stringify('Q38 — Heilmann rejected theory because of apparent absence of ................ in dinosaurs.'), options: JSON.stringify(null), answer: JSON.stringify('collarbones'), marks: 1 },
    { id: 'q-off-39', sectionId: 's-off-10', qType: 'SENTENCE_COMPLETION', prompt: JSON.stringify('Q39 — Feduccia and Martin believe ancestor was early ........ .'), options: JSON.stringify(null), answer: JSON.stringify('reptile'), marks: 1 },
    { id: 'q-off-40', sectionId: 's-off-10', qType: 'SENTENCE_COMPLETION', prompt: JSON.stringify('Q40 — In cladistics, the ............... between characteristics are of major importance.'), options: JSON.stringify(null), answer: JSON.stringify('similarities'), marks: 1 },
  ],
};

export function seedIfEmpty(db: any): { seeded: boolean; counts: { tests: number; sections: number; questions: number } } {
  try {
    const rows = db.prepare('SELECT * FROM tests').all();
    const qRows = db.prepare('SELECT * FROM questions').all();
    const existingTests = Array.isArray(rows) ? rows.length : 0;
    const existingQs = Array.isArray(qRows) ? qRows.length : 0;
    // if counts match DEMO, skip; if mismatch (e.g. upgraded from 17 to 35), reseed
    if (existingTests === DEMO_TESTS.tests.length && existingQs === DEMO_TESTS.questions.length) {
      return { seeded: false, counts: { tests: existingTests, sections: 0, questions: existingQs } };
    }
    if (existingTests > 0 && existingTests !== DEMO_TESTS.tests.length) {
      // clear old demo data to upgrade
      try {
        for (const t of DEMO_TESTS.tests) {
          try { db.prepare('DELETE FROM questions WHERE sectionId IN (SELECT id FROM sections WHERE testId = ?)').run(t.id); } catch {}
          try { db.prepare('DELETE FROM sections WHERE testId = ?').run(t.id); } catch {}
          try { db.prepare('DELETE FROM tests WHERE id = ?').run(t.id); } catch {}
        }
        // also clear fallback JSON directly if needed
        try {
          const allQs = db.prepare('SELECT * FROM questions').all();
          if (Array.isArray(allQs) && allQs.length === 0) {
            // fallback will be repopulated below
          }
        } catch {}
      } catch {}
    } else if (existingTests > 0) {
      return { seeded: false, counts: { tests: existingTests, sections: 0, questions: existingQs } };
    }
  } catch {}
  // seed
  try {
    const insertTest = db.prepare('INSERT OR REPLACE INTO tests (id, kind, title, durationSec, createdAt) VALUES (?,?,?,?,?)');
    for (const t of DEMO_TESTS.tests) insertTest.run(t.id, t.kind, t.title, t.durationSec, new Date().toISOString());
    const insertPassage = db.prepare('INSERT OR REPLACE INTO passages (id, title, body) VALUES (?,?,?)');
    for (const p of DEMO_TESTS.passages) insertPassage.run(p.id, p.title, p.body);
    const insertSection = db.prepare('INSERT OR REPLACE INTO sections (id, testId, type, title, audioPath, passageId) VALUES (?,?,?,?,?,?)');
    for (const s of DEMO_TESTS.sections) insertSection.run(s.id, s.testId, s.type, s.title, (s as any).audioPath ?? null, (s as any).passageId ?? null);
    const insertQ = db.prepare('INSERT OR REPLACE INTO questions (id, sectionId, qType, prompt, options, answer, marks) VALUES (?,?,?,?,?,?,?)');
    for (const q of DEMO_TESTS.questions) insertQ.run(q.id, q.sectionId, q.qType, q.prompt, q.options, q.answer, q.marks);
    return { seeded: true, counts: { tests: DEMO_TESTS.tests.length, sections: DEMO_TESTS.sections.length, questions: DEMO_TESTS.questions.length } };
  } catch (e) {
    return { seeded: false, counts: { tests: 0, sections: 0, questions: 0 } };
  }
}
